recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'
urlpatterns = [
  path('', views.index, name='index'),
  path('new/', views.new, name='new'),
  path('search/', views.search, name='search'),
  path('<int:recipe_id>/', views.recipe, name='recipe'),
  path('<int:recipe_id>/add_ingredient/', views.add_ingredient, name='add_ingredient'),
  path('<int:recipe_id>/add_instructions/', views.add_instructions, name='add_instructions')
]

recipesite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('login/', LoginView.as_view(template_name='recipes/login.html')),
    path('admin/', admin.site.urls),
    path('recipes/', include('recipes.urls')),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

class Recipe(models.Model):
  name = models.CharField(max_length=200)
  instructions = models.CharField(max_length=400)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.name

class Ingredient(models.Model):
  name = models.CharField(max_length=200)

  def __str__(self):
    return self.name

class Measurement(models.Model):
  quantity = models.IntegerField(default=1)
  unit = models.CharField(max_length=20)
  recipes = models.ManyToManyField(Recipe)
  ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)

recipes/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import Recipe, Ingredient, Measurement
from django.contrib.auth.models import User
import sqlite3

@login_required
def index(request):
  user = User.objects.get(username=request.user)
  recipes = Recipe.objects.filter(user=user)
  return render(request, 'recipes/index.html', {'recipe_list': recipes})

# FIX FLAW 2: add login_required annotation and replace recipe with outcommented line
# @login_required
def recipe(request, recipe_id):
  # recipe = get_object_or_404(Recipe, pk=recipe_id, user=User.objects.get(username=request.user))
  recipe = get_object_or_404(Recipe, pk=recipe_id)
  return render(request, 'recipes/recipe.html', {'recipe': recipe})

# FIX FLAW 1: fixes are commented out, also two changes needed in recipe.html
@login_required
def add_ingredient(request, recipe_id):
  recipe = get_object_or_404(Recipe, pk=recipe_id)
  try:
    added_ingredient = Ingredient.objects.get_or_create(
      name=request.GET.get('name'), # name=request.POST.get('name'),
    )
    added_measurement = Measurement.objects.get_or_create(
      quantity=int(request.GET.get('quantity')), # quantity=int(request.POST.get('quantity')),
      unit=request.GET.get('unit'), # unit=request.POST.get('unit'),
      ingredient=added_ingredient[0]
    )
    recipe.measurement_set.add(added_measurement[0])
  except (ValueError):
    return render(request, 'recipes/recipe.html', {
          'recipe': recipe,
          # FIX FLAW 5: Replace error_message with
          # 'error_message': 'Wrong value type, check your input',
          'error_message': 'Something went wrong, please investigate:\n' + request.method + ' ' + request.path + '\n' + str(request.COOKIES) + '\n' + str(request.session),
        })
  else:
    return HttpResponseRedirect(reverse('recipes:recipe', args=(recipe.id,)))

@login_required
def add_instructions(request, recipe_id):
  recipe = get_object_or_404(Recipe, pk=recipe_id)
  recipe.instructions = request.POST['instructions']
  recipe.save()
  return HttpResponseRedirect(reverse('recipes:recipe', args=(recipe.id,)))

@login_required
def new(request):
  added_recipe = Recipe.objects.get_or_create(
    name=request.POST['name'],
    user=User.objects.get(username=request.user)
  )
  return HttpResponseRedirect(reverse('recipes:index'))

@login_required
def search(request):
  user = User.objects.get(username=request.user)
  #FIX FLAW 3: replace lines 66-71 with
  # recipes = Recipe.objects.filter(user=user, name__icontains=request.GET['keyword'])
  connection = sqlite3.connect('recipes.db')
  cursor = connection.cursor()
  response = cursor.execute("SELECT * FROM recipes_recipe WHERE user_id='%s' and name LIKE '%%%s%%'" % (user.id, request.GET['keyword'])).fetchall()
  recipes = []
  for recipe in response:
    recipes.append({'id': recipe[0], 'name': recipe[1]})
  return render(request, 'recipes/index.html', {'recipe_list': recipes})

recipes/templates/recipes/index.html
<form action="{% url 'recipes:search' %}" method="get">
    <label for="name">Search</label><br/>
    <input type="text" name="keyword"><br/>
    <input type="submit" value="Search">
</form>
{% if recipe_list %}
    <ul>
    {% for recipe in recipe_list %}
        <li><a href="{% url 'recipes:recipe' recipe.id %}">{{ recipe.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No recipes are available.</p>
{% endif %}
<form action="{% url 'recipes:new' %}" method="post">
    {% csrf_token %}
    <label for="name">Add recipe</label><br/>
    <input type="text" name="name"><br/>
    <input type="submit" value="Submit">
</form>

recipes/templates/recipes/login.html
<h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>

recipes/templates/recipes/recipe.html
{% load static %}
<link rel="stylesheet" href="{% static 'recipes/style.css' %}">

<a href="{% url 'recipes:index' %}"><- Back</a>
<h1>{{ recipe.name }}</h1>
<div id="wrapper">
  <div id="div1">
    <ul>
      {% for ingredient in recipe.measurement_set.all %}
        <li><strong>{{ ingredient.quantity }} {{ ingredient.unit }}</strong> {{ ingredient.ingredient.name }}</li>
      {% endfor %}
    </ul>
  </div>
  <div id="div2">
    <!-- FIX FLAW 1: commented out, also changes needed in views.py -->
    <form action="{% url 'recipes:add_ingredient' recipe.id %}" method="GET"> <!-- Replace method="GET" with method="POST" -->
      <!-- add {% csrf_token %} -->
      <label for="name">Add ingredient</label><br/>
      <input type="text" name="name"><br/>
      <label for="quantity">Quantity</label><br/>
      <input type="text" name="quantity"><br/>
      <label for="unit">Unit</label><br/>
      <input type="text" name="unit"><br/>
      <input type="submit" value="Submit">
    </form>
    {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
    {% endif %}
  </div>
</div>

<p>{{ recipe.instructions }}</p>

<form action="{% url 'recipes:add_instructions' recipe.id %}" method="post">
  {% csrf_token %}
  <label for="instructions">Instructions</label><br/>
  <textarea name="instructions" rows="5" cols="40"></textarea><br/>
  <input type="submit" value="Submit">
</form>